@baseurl = http://localhost:8081

### Get Token
# @name getToken
GET {{baseurl}}/token

### Create Todo
DELETE  {{baseurl}}/todos/1
Content-Type: application/json
Authorization: Bearer {{getToken.response.body.$.token}}